import {test,expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {unzipSync,strFromU8} from 'fflate';
const url=pathToFileURL(path.resolve('dist/paneweave.html')).href,example=JSON.parse(fs.readFileSync('fixtures/workspace.json','utf8'));
async function open(page){await page.goto(url);await expect(page.locator('#projects input')).toHaveCount(2);await expect(page.locator('#build')).toBeEnabled();}
async function save(page,destination){const waiting=page.waitForEvent('download');await page.locator('#download').click();const download=await waiting;await download.saveAs(destination);return fs.readFileSync(destination);}
test('real offline ZIP before and after shared edit; responsive JA/EN review',async({page,context},info)=>{const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await context.setOffline(true);await open(page);await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();const before=await save(page,info.outputPath('before.zip'));const initial=unzipSync(before);expect(Object.keys(initial).sort()).toEqual(['README.txt','inputs/selected-workspace.json','layouts/alpha.kdl','layouts/beta.kdl','review.json']);for(const p of ['alpha','beta'])expect(strFromU8(initial[`layouts/${p}.kdl`])).toBe(fs.readFileSync(`evidence/generated/${p}-before.kdl`,'utf8'));
 await page.locator('#file').setInputFiles({name:'failed.json',mimeType:'application/json',buffer:Buffer.from('{')});await expect(page.locator('#status')).toHaveClass(/error/);await page.locator('#advanced').evaluate(e=>e.open=true);await page.locator('#workspace-json').fill('{');await page.locator('#apply-json').click();await expect(page.locator('#status')).toHaveClass(/error/);await page.locator('#discard-json').click();await page.locator('#advanced').evaluate(e=>e.open=false);
 await page.locator('#module-select').selectOption('tools');const source=await page.locator('#module-text').inputValue();await page.locator('#module-text').fill(source.replace('args "test"','args "test" "-race"'));await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#build')).toBeDisabled();await page.locator('#apply-module').click();await expect(page.locator('#build')).toBeEnabled();await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();await expect(page.locator('.effect.changed')).toHaveCount(2);
 const after=await save(page,info.outputPath('after.zip'));const changed=unzipSync(after);for(const p of ['alpha','beta'])expect(strFromU8(changed[`layouts/${p}.kdl`])).toBe(fs.readFileSync(`evidence/generated/${p}-after.kdl`,'utf8'));const repeated=await save(page,info.outputPath('repeated.zip'));expect(repeated.equals(after)).toBeTruthy();
 await page.screenshot({path:info.outputPath('desktop-ja.png'),fullPage:true});await page.locator('#language').click();await expect(page.locator('h1')).toContainText('Weave small');await page.screenshot({path:info.outputPath('desktop-en.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('#language').click();await page.screenshot({path:info.outputPath('mobile-ja.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.setViewportSize({width:1280,height:950});await page.addStyleTag({content:':root{font-size:200%}'});await page.screenshot({path:info.outputPath('enlarged-text-ja.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();expect(errors).toEqual([]);expect(external).toEqual([]);
});
test('keyboard project scope and inert strings; invalid edits lock export',async({page},info)=>{await open(page);await page.locator('#language').click();const alpha=page.locator('[data-project="alpha"]');await alpha.focus();await page.keyboard.press('Space');await expect(alpha).not.toBeChecked();await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();const selected=unzipSync(await save(page,info.outputPath('beta-only.zip')));expect(Object.keys(selected)).not.toContain('layouts/alpha.kdl');const manifest=JSON.parse(strFromU8(selected['inputs/selected-workspace.json']));expect(manifest.projects.map(p=>p.id)).toEqual(['beta']);expect(manifest.modules.map(m=>m.id)).toEqual(['frames','tools']);
 await page.locator('#module-select').selectOption('tools');const source=await page.locator('#module-text').inputValue();await page.locator('#module-text').fill(source.replace('notes with spaces.md','<img onerror=BAD>日本語.md'));await page.locator('#apply-module').click();await expect(page.locator('#build')).toBeEnabled();await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();expect(await page.locator('#output').inputValue()).toContain('<img onerror=BAD>');expect(await page.locator('img').count()).toBe(0);
 await page.locator('#module-text').fill('pane_template name="loop" {loop;}');await page.locator('#apply-module').click();await expect(page.locator('#status')).toContainText('Could not apply');await expect(page.locator('#download')).toBeDisabled();await expect(page.locator('#build')).toBeDisabled();await page.locator('#discard-module').click();await expect(page.locator('#module-text')).not.toHaveValue('pane_template name="loop" {loop;}');await expect(page.locator('#build')).toBeEnabled();
});
test('stale import, invalid UTF8, repeated same filename and failed-file/pending-JSON guards',async({page},info)=>{await open(page);await page.locator('#language').click();await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){const result=original.call(this);return this.name==='slow.json'?new Promise(r=>setTimeout(async()=>r(await result),650)):result;};});const altered=structuredClone(example);altered.projects[0].id='slow-marker';await page.locator('#file').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(altered))});await page.locator('#reset').click();await page.waitForTimeout(800);await expect(page.locator('[data-project="slow-marker"]')).toHaveCount(0);await page.locator('#module-select').selectOption('tools');await page.locator('#module-file').setInputFiles({name:'slow.json',mimeType:'text/plain',buffer:Buffer.from(example.modules[1].kdl.replace('args "test"','args "test" "STALE_MODULE_SENTINEL"'))});await page.locator('#reset').click();await page.waitForTimeout(800);expect(await page.locator('#workspace-json').inputValue()).not.toContain('STALE_MODULE_SENTINEL');
 await page.locator('#advanced').evaluate(e=>e.open=true);await page.locator('#workspace-json').fill('{DRAFT');await expect(page.locator('#build')).toBeDisabled();await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{PRIVATE_ERROR_SENTINEL')});await expect(page.locator('#status')).toContainText('Could not apply');await expect(page.locator('#workspace-json')).toHaveValue('{DRAFT');await expect(page.locator('#build')).toBeDisabled();expect(await page.locator('body').textContent()).not.toContain('PRIVATE_ERROR_SENTINEL');await page.locator('#discard-json').click();
 const bytes=Buffer.from(JSON.stringify(example));bytes[bytes.indexOf('notes with spaces.md')]=255;await page.locator('#file').setInputFiles({name:'same.json',mimeType:'application/json',buffer:bytes});await expect(page.locator('#status')).toContainText('Could not apply');await expect(page.locator('#file')).toHaveValue('');await page.locator('#file').setInputFiles({name:'same.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(example))});await expect(page.locator('#file-name')).toHaveText('same.json');await expect(page.locator('#build')).toBeEnabled();
 const longInput=structuredClone(example),longProject='A'.repeat(64),longModule='M'.repeat(64);longInput.projects[0].id=longProject;longInput.modules[1].id=longModule;for(const p of longInput.projects)p.modules=p.modules.map(id=>id==='tools'?longModule:id);await page.locator('#file').setInputFiles({name:'long-ids.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(longInput))});await expect(page.locator('#file-name')).toHaveText('long-ids.json');await page.setViewportSize({width:390,height:844});await page.locator('#module-select').selectOption(longModule);await page.locator('#build').click();await expect(page.locator('#download')).toBeEnabled();await page.locator('#result details').evaluateAll(nodes=>nodes.forEach(n=>n.open=true));await page.screenshot({path:info.outputPath('long-id-mobile.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.locator('#file').setInputFiles({name:'too-large.json',mimeType:'application/json',buffer:Buffer.alloc(1048577,32)});await expect(page.locator('#status')).toContainText('Could not apply');await expect(page.locator('#download')).toBeDisabled();
});
test('uniform CRLF edit preserves untouched bytes; worker failure cannot export',async({page})=>{await open(page);const input=structuredClone(example);input.modules[1].kdl=input.modules[1].kdl.replaceAll('\n','\r\n');await page.locator('#file').setInputFiles({name:'crlf.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(input))});await expect(page.locator('#file-name')).toHaveText('crlf.json');await page.locator('#module-select').selectOption('tools');await page.locator('#module-file').setInputFiles({name:'tools.kdl',mimeType:'text/plain',buffer:Buffer.from(input.modules[1].kdl)});await expect(page.locator('#status')).toContainText('モジュールと対象');await expect(page.locator('#module-file')).toHaveValue('');await page.locator('#module-file').setInputFiles({name:'bom.kdl',mimeType:'text/plain',buffer:Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),Buffer.from(input.modules[1].kdl)])});await expect(page.locator('#status')).toHaveClass(/error/);expect(JSON.parse(await page.locator('#workspace-json').inputValue()).modules[1].kdl).toBe(input.modules[1].kdl);await page.locator('#module-text').fill((await page.locator('#module-text').inputValue()).replace('args "test"','args "test" "-race"'));await page.locator('#apply-module').click();await expect(page.locator('#build')).toBeEnabled();const raw=JSON.parse(await page.locator('#workspace-json').inputValue());expect(raw.modules[1].kdl).toBe(input.modules[1].kdl.replace('args "test"','args "test" "-race"'));
 const mixed=structuredClone(input);mixed.modules[1].kdl=mixed.modules[1].kdl.replace('\r\n','\n');await page.locator('#file').setInputFiles({name:'mixed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(mixed))});await expect(page.locator('#file-name')).toHaveText('mixed.json');await expect(page.locator('#module-text')).toHaveJSProperty('readOnly',true);await expect(page.locator('#module-note')).toContainText('JSON');await page.locator('#language').click();await expect(page.locator('#module-note')).toContainText('mixes');await page.locator('#advanced').evaluate(e=>e.open=true);mixed.projects[0].id='mixed-json';await page.locator('#workspace-json').fill(JSON.stringify(mixed));await page.locator('#apply-json').click();await expect(page.locator('[data-project="mixed-json"]')).toHaveCount(1);await expect(page.locator('#module-note')).toContainText('mixes');await expect(page.locator('#module-text')).toHaveJSProperty('readOnly',true);
 await page.evaluate(()=>{window.Worker=class{constructor(){throw Error('unavailable');}};});await page.locator('#build').click();await expect(page.locator('#status')).toContainText('Worker');await expect(page.locator('#download')).toBeDisabled();
});
