import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {build,validateManifest,LIMITS} from '../src/engine.mjs';
const original=JSON.parse(fs.readFileSync('fixtures/workspace.json','utf8'));const clone=()=>structuredClone(original);const check=x=>build(JSON.stringify(x),['alpha','beta']);
test('two projects assemble ordinary layouts with all original blocks intact',()=>{const exports=check(original);assert.equal(exports.length,2);for(const e of exports){assert.ok(e.kdl.startsWith('// PaneWeave'));assert.ok(e.kdl.includes('layout {'));for(const map of e.sourceMap){const raw=new TextEncoder().encode(e.kdl).slice(map.startByte,map.endByte);assert.equal(new TextDecoder().decode(raw),map.originalText);assert.ok(e.kdl.includes(map.originalText));}assert.ok(e.kdl.includes('args "--clean" "notes with spaces.md"'));}assert.ok(!exports[1].kdl.includes('tab_template name="devTab"'));});
test('one shared edit changes both selected exports, original stays unchanged',()=>{const x=clone();x.modules[1].kdl=x.modules[1].kdl.replace('args "test"','args "test" "-race"');for(const e of check(x))assert.ok(e.kdl.includes('args "test" "-race"'));assert.ok(!JSON.stringify(original).includes('-race'));});
for(const [name,mutate] of [
 ['missing module',x=>x.projects[0].modules.push('absent')],['duplicate module id',x=>x.modules.push(structuredClone(x.modules[0]))],['duplicate project id',x=>x.projects.push(structuredClone(x.projects[0]))],['duplicate selected module',x=>x.projects[0].modules.push('tools')],['duplicate template',x=>x.modules[1].kdl+='pane_template name="topBar"\n'],['duplicate default',x=>x.modules[1].kdl+='default_tab_template { children; }\n'],['missing template',x=>x.projects[0].kdl='tab { missingPane; }'],['cycle',x=>x.modules[1].kdl+='pane_template name="cycleA" { cycleB; }\npane_template name="cycleB" { cycleA; }\n'],['multiple children',x=>x.modules[2].kdl='tab_template name="devTab" { children; children; }'],['children in project',x=>x.projects[0].kdl='tab { children; }'],['nested tab template',x=>x.projects[0].kdl='tab { devTab; }'],['contents_file',x=>x.projects[0].kdl='tab { pane { contents_file "/not-read"; }; }'],['unknown import node',x=>x.modules[1].kdl+='include "not-read"\n'],['duplicate property',x=>x.projects[0].kdl='tab name="a" name="b" {pane;}'],['duplicate property child',x=>x.projects[0].kdl='tab {pane command="a" {command "b";};}'],['unsupported syntax tag',x=>x.projects[0].kdl='(tag)tab {pane;}'],['invalid KDL',x=>x.projects[0].kdl='tab {'],['too many modules',x=>x.modules=Array(17).fill(x.modules[0])],['too many projects',x=>x.projects=Array(17).fill(x.projects[0])]])test(`reject ${name}`,()=>{const x=clone();mutate(x);assert.throws(()=>check(x));});
test('exponential repeated references are bounded using occurrence counts',()=>{const x=clone();x.modules=[{id:'many',kdl:'pane_template name="p0"\n'+Array.from({length:20},(_,i)=>`pane_template name="p${i+1}" { p${i}; p${i}; }`).join('\n')}];x.projects=[{id:'alpha',modules:['many'],kdl:'tab {p20;}'}];assert.throws(()=>build(JSON.stringify(x),['alpha']),/expanded-template-limit/);});
test('default template applications count toward expansion limit',()=>{const x=clone();x.modules=[{id:'many',kdl:'pane_template name="p0"\n'+Array.from({length:10},(_,i)=>`pane_template name="p${i+1}" { p${i}; p${i}; }`).join('\n')+'\ndefault_tab_template {p10;children;}'}];x.projects=[{id:'alpha',modules:['many'],kdl:Array(16).fill('tab {pane;}').join('\n')}];assert.throws(()=>build(JSON.stringify(x),['alpha']),/expanded-template-limit/);});
test('source map counts all accepted KDL newline sequences while keeping bytes',()=>{for(const newline of ['\n','\r\n','\r','\u0085','\u2028','\u2029']){const x=clone();x.modules[1].kdl=x.modules[1].kdl.replaceAll('\n',newline);const e=check(x)[0],m=e.sourceMap.find(m=>m.id==='tools');assert.equal(m.endLine-m.startLine,6);assert.equal(new TextDecoder().decode(new TextEncoder().encode(e.kdl).slice(m.startByte,m.endByte)),x.modules[1].kdl);}});
test('input bytes and template count are bounded',()=>{assert.throws(()=>validateManifest(' '.repeat(LIMITS.bytes+1)),/input-byte-limit/);const x=clone();x.modules[1].kdl=Array.from({length:65},(_,i)=>`pane_template name="p${i}"`).join('\n');assert.throws(()=>check(x),/template-count-limit/);});
test('unknown/repeated selections reject',()=>{assert.throws(()=>build(JSON.stringify(original),['absent']));assert.throws(()=>build(JSON.stringify(original),['alpha','alpha']));});
